name: provider_counter
description: >
  The starter Flutter application, but using Provider to manage state.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  cupertino_icons: ^1.0.3
  dio: ^5.3.2

flutter:
  uses-material-design: true
